import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file: string) => readFileSync(path.join(root, file), 'utf8')

const schema = read('prisma/schema.prisma')
const migration = read('prisma/migrations/20260809113000_add_material_sales_price/migration.sql')
const pricingRule = read('modules/sales/domain/sales-order-pricing.ts')
const salesCommand = read('modules/sales/server/sales-order-command-service.ts')
const fulfillmentSchema = read('modules/sales/contracts/fulfillment-schema.ts')
const fulfillmentCommand = read('modules/sales/server/fulfillment-command-service.ts')
const shipmentApi = read('app/api/shipments/route.ts')
const salesPage = read('modules/sales/ui/SalesOrderPageModule.tsx')
const shipmentDialog = read('modules/sales/ui/ShipmentCreateDialog.tsx')
const shippableApi = read('app/api/sales-orders/shippable/route.ts')

assert.match(schema, /defaultSalePrice\s+Float\?/, '物料必须提供可空默认销售价')
assert.doesNotMatch(schema.match(/model Material \{[\s\S]*?\n\}/)?.[0] || '', /costPrice|defaultCost/, '物料主数据不得增加默认成本价字段')
assert.match(schema, /defaultSalePriceSnapshot\s+Float\?/, '销售明细必须冻结默认销售价快照')
assert.match(schema, /priceAdjustedAt\s+DateTime\?/, '销售明细必须记录调价时间')
assert.match(migration, /ALTER TABLE "Material" ADD COLUMN "defaultSalePrice"/, '迁移必须增加物料默认销售价')
assert.match(pricingRule, /priceSource: defaultSalePrice/, '创建订单必须在领域规则中判定默认价或手工价来源')
assert.match(pricingRule, /defaultSalePriceSnapshot: defaultSalePrice/, '创建订单必须在领域规则中保存默认价快照')
assert.doesNotMatch(salesCommand, /发货记录|发货单/, '销售订单命令服务不得依赖发货记录')
assert.match(salesCommand, /action: 'ADJUST_PRICE'/, '调价必须在同一事务中写入审计日志')
assert.match(salesPage, /调整价格/, '销售订单页面必须提供受控调价入口')
assert.doesNotMatch(salesPage, /生成发货单/, '销售订单页面不得直接派生发货单')
assert.match(fulfillmentSchema, /materialId: z\.string\(\)\.min/, '发货明细必须直接选择物料')
assert.doesNotMatch(fulfillmentSchema, /salesOrderItemId/, '发货契约不得接收销售订单明细 ID')
assert.doesNotMatch(fulfillmentCommand, /salesOrderItem|salesOrderId/, '发货命令服务不得保存销售订单关联')
assert.match(fulfillmentCommand, /defaultSalePrice/, '发货必须调用物料默认销售价')
assert.match(shipmentApi, /createManagedShipment/, '发货路由必须通过领域命令服务创建单据')
assert.doesNotMatch(shipmentApi, /@\/lib\/prisma|\bprisma\./, '发货路由不得直接访问 Prisma')
assert.match(shipmentDialog, /不关联销售订单/, '发货界面必须明确完全解耦')
assert.match(shippableApi, /requireResourcePermission\('shipment', 'create'\)/, '发货选项必须只依赖发货创建权限')
assert.match(shippableApi, /getShipmentCreateOptions/, '发货选项接口必须通过领域查询服务提供客户、物料与汇总参考')

console.log('销售价与发货边界验证通过：默认价快照、受控调价、订单/发货完全解耦及无物料成本价字段均已落实。')
