import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const read = (path: string) => readFileSync(join(root, path), 'utf8')

const registry = read('app/components/shell/WorkspacePageRendererRegistry.tsx')
const materialsIndex = read('modules/materials/index.ts')
const materialPage = read('modules/materials/ui/MaterialPage.tsx')
const materialDetailDialog = read('modules/materials/ui/MaterialDetailDialog.tsx')
const materialEditDialog = read('modules/materials/ui/MaterialEditDialog.tsx')
const materialImportDialog = read('modules/materials/ui/MaterialImportDialog.tsx')
const materialOptions = read('modules/materials/model/material-options.ts')
const materialClient = read('modules/materials/client/materials-api.ts')
const materialContracts = read('modules/materials/contracts/material.ts')
const bomIndex = read('modules/bom/index.ts')
const bomOverview = read('modules/bom/ui/BomOverviewPage.tsx')
const bomClient = read('modules/bom/client/bom-api.ts')
const bomContracts = read('modules/bom/contracts/bom.ts')

assert.equal(existsSync(join(root, 'app/components/MaterialPage.tsx')), false, '物料领域页面不得回流公共 components 根目录')
assert.equal(existsSync(join(root, 'app/components/MaterialPanoramaPage.tsx')), false, '物料全景页面不得回流公共 components 根目录')
assert.equal(existsSync(join(root, 'app/components/BomOverviewPage.tsx')), false, 'BOM 领域页面不得回流公共 components 根目录')

assert.match(registry, /import\('\@\/modules\/materials'\)/, '页面注册必须从 materials 模块公开出口加载')
assert.match(registry, /import\('\@\/modules\/bom'\)/, '页面注册必须从 bom 模块公开出口加载')
assert.match(materialsIndex, /from '\.\/ui\/MaterialPage'/, 'materials 模块必须拥有唯一页面公开出口')
assert.match(materialsIndex, /from '\.\/contracts'/, 'materials 模块必须通过公开出口暴露稳定契约')
assert.match(bomIndex, /from '\.\/ui\/BomOverviewPage'/, 'bom 模块必须拥有唯一页面公开出口')
assert.match(bomIndex, /from '\.\/contracts'/, 'bom 模块必须通过公开出口暴露稳定契约')

assert.match(materialPage, /from '\.\.\/client'/, '物料页面必须通过本模块 client 访问数据')
assert.match(materialPage, /from '\@\/modules\/bom'/, '物料页面调用 BOM 能力必须经过 bom 模块公开出口')
assert.match(materialPage, /from '\.\/MaterialEditDialog'/, '物料页面必须复用领域编辑切片')
assert.match(materialPage, /from '\.\/MaterialDetailDialog'/, '物料页面必须复用领域详情切片')
assert.match(materialPage, /from '\.\/MaterialImportDialog'/, '物料页面必须复用领域导入切片')
assert.doesNotMatch(materialPage, /fetch\(/, '物料页面 UI 不得直接发起 HTTP 请求')
assert.doesNotMatch(materialPage, /saveMaterial|importMaterials|findMaterialByCode|createEmptyMaterialForm/, '主物料页面不得重新承载详情读取、保存、导入或表单初始化状态')
assert.match(materialDetailDialog, /findMaterialByCode/, '物料详情切片必须拥有详情重新读取动作')
assert.match(materialDetailDialog, /AttachmentPanel/, '物料详情切片必须拥有图片附件视图')
assert.match(materialEditDialog, /saveMaterial/, '物料编辑切片必须拥有保存动作')
assert.match(materialEditDialog, /createMaterialForm/, '物料编辑切片必须拥有表单初始化')
assert.match(materialImportDialog, /importMaterials/, '物料导入切片必须拥有导入动作')
assert.match(materialOptions, /materialCategoryOptions/, '物料列表与编辑器必须复用领域选项定义')
assert.doesNotMatch(materialEditDialog, /fetch\(/, '物料编辑 UI 不得直接发起 HTTP 请求')
assert.doesNotMatch(materialImportDialog, /fetch\(/, '物料导入 UI 不得直接发起 HTTP 请求')
assert.doesNotMatch(materialDetailDialog, /fetch\(/, '物料详情 UI 必须通过领域 client 读取数据')
assert.doesNotMatch(bomOverview, /fetch\(/, 'BOM 全览 UI 不得直接发起 HTTP 请求')
assert.match(materialClient, /fetch\('\/api\/materials/, '物料 HTTP 访问必须集中在 materials client')
assert.match(bomClient, /fetch\('\/api\/boms/, 'BOM HTTP 访问必须集中在 bom client')
assert.match(materialContracts, /export interface Material/, '物料数据结构必须集中为领域契约')
assert.match(bomContracts, /export interface BomVersion/, 'BOM 数据结构必须集中为领域契约')

assert.ok(materialPage.split('\n').length <= 2450, '物料页面已拆出详情、编辑与导入切片，不得再超过 2450 行')
assert.ok(materialDetailDialog.split('\n').length <= 180, '物料详情切片不得重新膨胀为页面级巨型组件')
assert.ok(materialEditDialog.split('\n').length <= 450, '物料编辑切片不得重新膨胀为页面级巨型组件')
assert.ok(materialImportDialog.split('\n').length <= 160, '物料导入切片应保持单一职责')
assert.ok(bomOverview.split('\n').length <= 500, 'BOM 全览页面不得超过 500 行')

console.log('物料/BOM 模块边界验证通过：页面归属、公开出口、数据契约、HTTP client、详情、编辑与导入切片已分离。')
