import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const server = readFileSync('services/cad-preview/server.py', 'utf8')
const dockerfile = readFileSync('services/cad-preview/Dockerfile', 'utf8')
const entrypoint = readFileSync('services/cad-preview/entrypoint.sh', 'utf8')
const smokeTest = readFileSync('services/cad-preview/smoke_test.py', 'utf8')
const requirements = readFileSync('services/cad-preview/requirements.txt', 'utf8')
const readme = readFileSync('services/cad-preview/README.md', 'utf8')
const adr = readFileSync('docs/adr/0046-isolated-cad-preview-converter.md', 'utf8')
const deployment = readFileSync('docs/deployment/coolify.md', 'utf8')
const cadDeployment = readFileSync('docs/deployment/LibreDWG-Coolify配置手册.md', 'utf8')
const cadClient = readFileSync('lib/files/cad-document-preview.ts', 'utf8')
const thumbnail = readFileSync('modules/attachments/ui/DocumentPreviewThumb.tsx', 'utf8')

assert.match(server, /self\.path != "\/health"/, '服务必须实现健康检查')
assert.match(server, /self\.path != "\/v1\/convert\/pdf"/, '服务必须实现既有 PDF 转换契约')
assert.match(server, /hmac\.compare_digest/, 'Bearer 令牌必须使用恒定时间比较')
assert.match(server, /MAX_UPLOAD_BYTES/, '上传必须有尺寸上限')
assert.match(server, /TemporaryDirectory/, '转换必须使用自动清理的隔离临时目录')
assert.match(server, /startswith\(b"%PDF-"\)/, '服务必须校验 PDF 响应签名')
assert.match(server, /extension not in \{"\.dwg", "\.dxf"\}/, '服务只能接受 DWG/DXF')
assert.match(server, /command = \["dwg2dxf"\]/, 'DWG 必须先经 LibreDWG 转为 DXF')
assert.match(server, /for minimal in \(False, True\)/, '完整 DXF 无法解析时必须降级到 LibreDWG 最小模式')
assert.match(server, /apply_cad_font_fallbacks\(document\)/, 'DXF 渲染前必须应用 CAD 字体回退')
assert.match(server, /NotoSansCJKsc-Regular\.otf/, '缺失 SHX 与大字体必须回退到内置中文字体')
assert.match(server, /CAD_PREVIEW_FONT_DIRS/, '转换器必须支持挂载企业 CAD 字体目录')
assert.match(server, /fonts\.build_system_font_cache\(\)/, '挂载字体后必须重建 ezdxf 字体缓存')
assert.match(server, /inspect_cad_font_directory/, '转换器必须检查字体目标目录的所有者与权限')
assert.match(server, /current_cad_font_directory_status\(\)/, '健康检查必须实时复查字体目录权限状态')
assert.match(server, /HTTPStatus\.SERVICE_UNAVAILABLE/, '字体挂载失效后健康检查必须返回不可用')
assert.match(server, /status = "permission_denied"/, '已配置但不可读的字体目录必须明确失败')
assert.match(server, /text_style\.dxf\.bigfont = ""/, '大字体缺失时必须清除失效引用再使用中文回退字体')
assert.match(server, /BoundedSemaphore\(MAX_CONCURRENT_CONVERSIONS\)/, '转换器必须限制同时执行的 CAD 转换数量')
assert.match(cadClient, /withConversionSlot/, 'MES 主应用必须在请求转换服务前排队')
assert.match(thumbnail, /loading="lazy"/, '文档列表缩略图必须延迟加载，避免一次触发整页 CAD 转换')

assert.match(dockerfile, /ARG LIBREDWG_VERSION=0\.14/, 'LibreDWG 必须固定到已审查版本')
assert.match(dockerfile, /ARG LIBREDWG_SHA256=[0-9a-f]{64}/, 'LibreDWG 源码必须校验 SHA-256')
assert.match(dockerfile, /--max-time 600/, '源码下载必须有有限超时')
assert.match(dockerfile, /--disable-bindings/, 'LibreDWG 编译阶段不得引入未使用的语言绑定')
assert.match(dockerfile, /--disable-python/, 'LibreDWG 编译阶段不得引入未使用的 Python 绑定')
assert.match(dockerfile, /--disable-json/, 'CAD 预览服务不得编译未使用且耗时的 JSON 转换模块')
assert.match(dockerfile, /--disable-docs/, 'CAD 预览服务不得编译未使用的 LibreDWG 文档')
assert.match(dockerfile, /make -C src/, 'LibreDWG 构建必须限定在核心库目录')
assert.match(dockerfile, /make -C programs/, 'LibreDWG 构建必须限定在命令行工具目录并跳过无关示例')
assert.match(dockerfile, /ENTRYPOINT \["\/usr\/local\/bin\/cad-preview-entrypoint\.sh"\]/, '运行容器必须先通过受控入口修复字体目录')
assert.match(dockerfile, /HEALTHCHECK/, '运行镜像必须提供容器健康检查')
assert.match(dockerfile, /cad-preview-entrypoint\.sh python smoke_test\.py/, '镜像构建必须经过真实入口执行转换冒烟测试')
assert.match(dockerfile, /CAD_PREVIEW_FONT_DIRS=\/usr\/local\/share\/fonts\/mes-lite:\/opt\/cad-fonts/, '镜像必须声明内置与外挂字体目录')
assert.match(dockerfile, /CAD_PREVIEW_MANAGED_FONT_DIRS=\/opt\/cad-fonts/, '镜像必须只声明受控的权限修复目录')

assert.match(entrypoint, /\/opt\/cad-fonts\|\/opt\/cad-fonts\/\*/, '入口必须拒绝修改外挂字体白名单之外的路径')
assert.match(entrypoint, /chown -R root:cadpreview/, '入口必须修正外挂字体目录的所有者与组')
assert.match(entrypoint, /-type d -exec chmod 0750/, '入口必须把外挂字体目录限制为组只读可进入')
assert.match(entrypoint, /-type f -exec chmod 0640/, '入口必须把外挂字体文件限制为组只读')
assert.match(entrypoint, /--reuid=cadpreview/, '权限修复后必须降为专用转换用户')
assert.match(entrypoint, /--bounding-set=-all/, '降权时必须清空 capability bounding set')
assert.match(entrypoint, /--inh-caps=-all/, '降权时必须清空 inheritable capabilities')
assert.match(entrypoint, /--ambient-caps=-all/, '降权时必须清空 ambient capabilities')
assert.match(entrypoint, /--no-new-privs/, '降权时必须禁止重新获得更高权限')
assert.match(entrypoint, /export HOME=\/home\/cadpreview/, '降权后必须切换到专用用户主目录')
assert.match(entrypoint, /export XDG_CONFIG_HOME=\/home\/cadpreview\/\.config/, '降权后不得继续读取 root 配置目录')
assert.match(entrypoint, /-type l -print -quit/, '权限修复前必须拒绝字体目录中的符号链接')

assert.match(smokeTest, /convert_source_to_pdf\(source_dxf, dxf_pdf\)/, '镜像冒烟必须覆盖 DXF 直转')
assert.match(smokeTest, /\["dxf2dwg", "-y", "-o"/, '镜像冒烟必须生成真实 DWG 测试夹具')
assert.match(smokeTest, /convert_source_to_pdf\(source_dwg, dwg_pdf\)/, '镜像冒烟必须覆盖 DWG 转换')
assert.match(smokeTest, /document\.styles\.add\("HZ", font="txt\.shx"\)/, '镜像冒烟必须覆盖缺失 SHX 中文字体回退')
assert.match(smokeTest, /restricted_target\.chmod\(0\)/, '镜像冒烟必须以非 root 用户验证字体目录权限拒绝')
assert.match(requirements, /^ezdxf==/m, 'DXF 渲染依赖必须固定版本')
assert.match(requirements, /^PyMuPDF==/m, 'PDF 渲染依赖必须固定版本')

for (const source of [readme, adr, deployment]) {
  assert.match(source, /LibreDWG/, '服务说明、架构决策和部署文档必须写明 LibreDWG')
}
assert.match(readme, /GPL-3\.0-or-later/, '交付说明必须写明 LibreDWG 许可证')
assert.match(readme, /AGPL-3\.0-or-later/, '交付说明必须写明 PyMuPDF 许可证')
assert.match(deployment, /services\/cad-preview\/Dockerfile/, 'Coolify 文档必须给出独立服务 Dockerfile')
assert.match(deployment, /不(?:得)?暴露公网/, 'Coolify 文档必须锁定私网边界')
assert.doesNotMatch(cadDeployment, /\/opt\/cad-fonts` 只读持久挂载/, '外挂字体卷必须允许入口在启动阶段修复权限')
for (const capability of ['CHOWN', 'FOWNER', 'DAC_OVERRIDE', 'SETUID', 'SETGID', 'SETPCAP']) {
  assert.match(cadDeployment, new RegExp(`--cap-add ${capability}`), `Coolify 加固参数必须保留启动降权所需的 ${capability}`)
}

console.log('LibreDWG CAD 预览服务结构、协议、安全边界与发布说明验证通过')
