import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const read = (path: string) => readFileSync(join(root, path), 'utf8')

const registry = read('app/components/shell/WorkspacePageRendererRegistry.tsx')
const materialsIndex = read('modules/materials/index.ts')
const materialPage = read('modules/materials/ui/MaterialPage.tsx')
const materialCardView = read('modules/materials/ui/MaterialCardView.tsx')
const materialDetailDialog = read('modules/materials/ui/MaterialDetailDialog.tsx')
const materialEditDialog = read('modules/materials/ui/MaterialEditDialog.tsx')
const materialImportDialog = read('modules/materials/ui/MaterialImportDialog.tsx')
const materialPagination = read('modules/materials/ui/MaterialPagination.tsx')
const materialTableView = read('modules/materials/ui/MaterialTableView.tsx')
const materialOptions = read('modules/materials/model/material-options.ts')
const materialViewModel = read('modules/materials/model/material-view.ts')
const materialClient = read('modules/materials/client/materials-api.ts')
const materialContracts = read('modules/materials/contracts/material.ts')
const bomIndex = read('modules/bom/index.ts')
const bomOverview = read('modules/bom/ui/BomOverviewPage.tsx')
const bomClient = read('modules/bom/client/bom-api.ts')
const bomContracts = read('modules/bom/contracts/bom.ts')

assert.equal(existsSync(join(root, 'app/components/MaterialPage.tsx')), false, '物料领域页面不得回流公共 components 根目录')
assert.equal(existsSync(join(root, 'app/components/MaterialPanoramaPage.tsx')), false, '物料全景页面不得回流公共 components 根目录')
assert.equal(existsSync(join(root, 'app/components/BomOverviewPage.tsx')), false, 'BOM 领域页面不得回流公共 components 根目录')

assert.match(registry, /import\('\@\/modules\/materials'\)/, '页面注册必须从 materials 模块公开出口加载')
assert.match(registry, /import\('\@\/modules\/bom'\)/, '页面注册必须从 bom 模块公开出口加载')
assert.match(materialsIndex, /from '\.\/ui\/MaterialPage'/, 'materials 模块必须拥有唯一页面公开出口')
assert.match(materialsIndex, /from '\.\/contracts'/, 'materials 模块必须通过公开出口暴露稳定契约')
assert.match(bomIndex, /from '\.\/ui\/BomOverviewPage'/, 'bom 模块必须拥有唯一页面公开出口')
assert.match(bomIndex, /from '\.\/contracts'/, 'bom 模块必须通过公开出口暴露稳定契约')

assert.match(materialPage, /from '\.\.\/client'/, '物料页面必须通过本模块 client 访问数据')
assert.match(materialPage, /from '\@\/modules\/bom'/, '物料页面调用 BOM 能力必须经过 bom 模块公开出口')
assert.match(materialPage, /from '\.\/MaterialEditDialog'/, '物料页面必须复用领域编辑切片')
assert.match(materialPage, /from '\.\/MaterialDetailDialog'/, '物料页面必须复用领域详情切片')
assert.match(materialPage, /from '\.\/MaterialImportDialog'/, '物料页面必须复用领域导入切片')
assert.match(materialPage, /from '\.\/MaterialCardView'/, '物料页面必须复用领域卡片视图')
assert.match(materialPage, /from '\.\/MaterialTableView'/, '物料页面必须复用领域表格视图')
assert.match(materialPage, /from '\.\/MaterialPagination'/, '物料页面必须复用领域分页视图')
assert.doesNotMatch(materialPage, /fetch\(/, '物料页面 UI 不得直接发起 HTTP 请求')
assert.doesNotMatch(materialPage, /saveMaterial|importMaterials|findMaterialByCode|createEmptyMaterialForm/, '主物料页面不得重新承载详情读取、保存、导入或表单初始化状态')
assert.doesNotMatch(materialPage, /materials\.map/, '主物料页面不得重新展开卡片或表格行')
assert.match(materialDetailDialog, /findMaterialByCode/, '物料详情切片必须拥有详情重新读取动作')
assert.match(materialDetailDialog, /AttachmentPanel/, '物料详情切片必须拥有图片附件视图')
assert.match(materialEditDialog, /saveMaterial/, '物料编辑切片必须拥有保存动作')
assert.match(materialEditDialog, /createMaterialForm/, '物料编辑切片必须拥有表单初始化')
assert.match(materialImportDialog, /importMaterials/, '物料导入切片必须拥有导入动作')
assert.match(materialOptions, /materialCategoryOptions/, '物料列表与编辑器必须复用领域选项定义')
assert.match(materialViewModel, /MaterialCollectionActions/, '物料集合视图必须通过稳定动作契约与主页面协作')
assert.match(materialCardView, /materials\.map/, '物料卡片视图必须拥有卡片集合渲染')
assert.match(materialTableView, /<table/, '物料表格视图必须拥有表格和列头渲染')
assert.doesNotMatch(materialEditDialog, /fetch\(/, '物料编辑 UI 不得直接发起 HTTP 请求')
assert.doesNotMatch(materialImportDialog, /fetch\(/, '物料导入 UI 不得直接发起 HTTP 请求')
assert.doesNotMatch(materialDetailDialog, /fetch\(/, '物料详情 UI 必须通过领域 client 读取数据')
assert.doesNotMatch(materialCardView, /fetch\(/, '物料卡片视图不得读取远端数据')
assert.doesNotMatch(materialTableView, /fetch\(/, '物料表格视图不得读取远端数据')
assert.doesNotMatch(bomOverview, /fetch\(/, 'BOM 全览 UI 不得直接发起 HTTP 请求')
assert.match(materialClient, /fetch\('\/api\/materials/, '物料 HTTP 访问必须集中在 materials client')
assert.match(bomClient, /fetch\('\/api\/boms/, 'BOM HTTP 访问必须集中在 bom client')
assert.match(materialContracts, /export interface Material/, '物料数据结构必须集中为领域契约')
assert.match(bomContracts, /export interface BomVersion/, 'BOM 数据结构必须集中为领域契约')

assert.ok(materialPage.split('\n').length <= 2050, '物料页面已拆出集合视图，不得再超过 2050 行')
assert.ok(materialCardView.split('\n').length <= 150, '物料卡片视图应保持纯展示职责')
assert.ok(materialTableView.split('\n').length <= 280, '物料表格视图不得承载页面级状态')
assert.ok(materialPagination.split('\n').length <= 80, '物料分页视图应保持纯展示职责')
assert.ok(materialViewModel.split('\n').length <= 130, '物料视图模型只能维护稳定选项和类型')
assert.ok(materialDetailDialog.split('\n').length <= 180, '物料详情切片不得重新膨胀为页面级巨型组件')
assert.ok(materialEditDialog.split('\n').length <= 450, '物料编辑切片不得重新膨胀为页面级巨型组件')
assert.ok(materialImportDialog.split('\n').length <= 160, '物料导入切片应保持单一职责')
assert.ok(bomOverview.split('\n').length <= 500, 'BOM 全览页面不得超过 500 行')

console.log('物料/BOM 模块边界验证通过：数据访问、详情、编辑、导入、卡片、表格和分页职责已分离。')
