import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { validateBomStructure } from '../modules/bom/domain/bom-structure'
import { nextBomVersion } from '../modules/bom/domain/bom-version'
import { classifyMaterialAttachments } from '../modules/materials/server/material-panorama-attachments'
import { parseMaterialImportRows, readMaterialImportSheet } from '../modules/materials/domain/material-import-parser'
import { togglePanoramaSection } from '../modules/materials/model/material-panorama-view'
import { presetUnitCatalog } from '../lib/unit-catalog'

const root = process.cwd()
const read = (path: string) => readFileSync(join(root, path), 'utf8')

const registry = read('app/components/shell/WorkspacePageRendererRegistry.tsx')
const materialsIndex = read('modules/materials/index.ts')
const materialPage = read('modules/materials/ui/MaterialPage.tsx')
const materialWorkspaceToolbar = read('modules/materials/ui/MaterialWorkspaceToolbar.tsx')
const materialBomWorkspace = read('modules/materials/ui/MaterialBomWorkspace.tsx')
const materialPanoramaPage = read('modules/materials/ui/MaterialPanoramaPage.tsx')
const materialPanoramaDashboard = read('modules/materials/ui/material-panorama/MaterialPanoramaDashboard.tsx')
const materialPanoramaContracts = read('modules/materials/contracts/material-panorama.ts')
const materialPanoramaModel = read('modules/materials/model/material-panorama-view.ts')
const materialPanoramaOverview = read('modules/materials/ui/material-panorama/MaterialPanoramaOverviewModules.tsx')
const materialPanoramaOperations = read('modules/materials/ui/material-panorama/MaterialPanoramaOperationsModules.tsx')
const materialPanoramaRecords = read('modules/materials/ui/material-panorama/MaterialPanoramaRecordsModule.tsx')
const materialPanoramaLayout = read('modules/materials/ui/material-panorama/MaterialPanoramaLayoutDialog.tsx')
const materialPanoramaViewer = read('modules/materials/ui/material-panorama/MaterialPanoramaViewer.tsx')
const splitWorkspace = read('app/components/layout/SplitWorkspace.tsx')
const materialCardView = read('modules/materials/ui/MaterialCardView.tsx')
const materialDetailDialog = read('modules/materials/ui/MaterialDetailDialog.tsx')
const materialReferenceButton = read('modules/materials/ui/MaterialReferenceButton.tsx')
const materialDetailController = read('modules/materials/ui/useMaterialDetail.ts')
const materialEditDialog = read('modules/materials/ui/MaterialEditDialog.tsx')
const materialImportDialog = read('modules/materials/ui/MaterialImportDialog.tsx')
const materialPageOptions = read('modules/materials/ui/MaterialPageOptions.tsx')
const materialPagination = read('modules/materials/ui/MaterialPagination.tsx')
const materialTableView = read('modules/materials/ui/MaterialTableView.tsx')
const materialViewPreferences = read('modules/materials/ui/useMaterialViewPreferences.ts')
const materialOptions = read('modules/materials/model/material-options.ts')
const materialViewModel = read('modules/materials/model/material-view.ts')
const materialClient = read('modules/materials/client/materials-api.ts')
const materialContracts = read('modules/materials/contracts/material.ts')
const materialPanoramaRoute = read('app/api/materials/[id]/panorama/route.ts')
const materialPanoramaQueryService = read('modules/materials/server/material-panorama-query-service.ts')
const materialPanoramaAttachmentService = read('modules/materials/server/material-panorama-attachments.ts')
const materialImportRoute = read('app/api/materials/import/route.ts')
const materialImportService = read('modules/materials/server/material-import-service.ts')
const materialImportParser = read('modules/materials/domain/material-import-parser.ts')
const bomIndex = read('modules/bom/index.ts')
const bomOverview = read('modules/bom/ui/BomOverviewPage.tsx')
const bomDraftEditor = read('modules/bom/ui/BomDraftEditor.tsx')
const bomDraftController = read('modules/bom/ui/useBomDraftController.ts')
const bomDraftModel = read('modules/bom/model/bom-draft.ts')
const bomClient = read('modules/bom/client/bom-api.ts')
const bomContracts = read('modules/bom/contracts/bom.ts')
const bomRoute = read('app/api/boms/route.ts')
const bomQueryService = read('modules/bom/server/bom-query-service.ts')
const bomCommandService = read('modules/bom/server/bom-command-service.ts')
const bomLifecycleService = read('modules/bom/server/bom-lifecycle-service.ts')
const bomSchema = read('modules/bom/contracts/bom-schema.ts')
const bomReleaseRoute = read('app/api/boms/[id]/release/route.ts')
const bomCopyRoute = read('app/api/boms/[id]/copy/route.ts')
const bomObsoleteRoute = read('app/api/boms/[id]/obsolete/route.ts')

assert.equal(existsSync(join(root, 'app/components/MaterialPage.tsx')), false, '物料领域页面不得回流公共 components 根目录')
assert.equal(existsSync(join(root, 'app/components/MaterialPanoramaPage.tsx')), false, '物料全景页面不得回流公共 components 根目录')
assert.equal(existsSync(join(root, 'app/components/BomOverviewPage.tsx')), false, 'BOM 领域页面不得回流公共 components 根目录')

assert.match(registry, /import\('\@\/modules\/materials'\)/, '页面注册必须从 materials 模块公开出口加载')
assert.match(registry, /import\('\@\/modules\/bom'\)/, '页面注册必须从 bom 模块公开出口加载')
assert.match(materialsIndex, /from '\.\/ui\/MaterialPage'/, 'materials 模块必须拥有唯一页面公开出口')
assert.match(materialsIndex, /from '\.\/contracts'/, 'materials 模块必须通过公开出口暴露稳定契约')
assert.match(materialsIndex, /MaterialDetailDialog/, 'materials 模块必须公开物料详情弹窗供关联业务复用')
assert.match(materialsIndex, /MaterialReferenceButton/, 'materials 模块必须公开统一的物料引用入口')
assert.match(bomIndex, /from '\.\/ui\/BomOverviewPage'/, 'bom 模块必须拥有唯一页面公开出口')
assert.match(bomIndex, /from '\.\/contracts'/, 'bom 模块必须通过公开出口暴露稳定契约')

assert.match(materialPage, /from '\.\.\/client'/, '物料页面必须通过本模块 client 访问数据')
assert.match(materialPage, /from '\@\/modules\/bom'/, '物料页面调用 BOM 能力必须经过 bom 模块公开出口')
assert.match(materialPage, /<BomDraftEditor controller=\{bomDraft\}/, '物料页面必须复用 BOM 领域草稿编辑器')
assert.match(materialPage, /useBomDraftController/, '物料页面不得自行维护 BOM 草稿状态')
assert.match(materialPage, /from '\.\/MaterialEditDialog'/, '物料页面必须复用领域编辑切片')
assert.match(materialPage, /from '\.\/MaterialDetailDialog'/, '物料页面必须复用领域详情切片')
assert.match(materialPage, /from '\.\/MaterialImportDialog'/, '物料页面必须复用领域导入切片')
assert.match(materialPage, /from '\.\/MaterialPageOptions'/, '物料页面必须复用领域页内选项切片')
assert.match(materialPage, /from '\.\/MaterialCardView'/, '物料页面必须复用领域卡片视图')
assert.match(materialPage, /from '\.\/MaterialTableView'/, '物料页面必须复用领域表格视图')
assert.match(materialPage, /from '\.\/MaterialPagination'/, '物料页面必须复用领域分页视图')
assert.match(materialPage, /from '\.\/MaterialWorkspaceToolbar'/, '物料页面必须复用双形态工具栏任务')
assert.match(materialPage, /from '\.\/MaterialBomWorkspace'/, '物料页面必须复用 BOM 工作区任务')
assert.match(materialPage, /from '\.\/useMaterialViewPreferences'/, '物料页面必须复用领域视图偏好控制器')
assert.doesNotMatch(materialPage, /fetch\(/, '物料页面 UI 不得直接发起 HTTP 请求')
assert.doesNotMatch(materialPanoramaPage, /fetch\(/, '物料全景协调页不得直接发起 HTTP 请求')
assert.match(materialPanoramaPage, /MaterialPanoramaDashboard/, '物料全景必须复用仪表台任务组件')
assert.match(materialPanoramaDashboard, /MaterialPanoramaSummaryModule/, '物料全景仪表台必须复用档案与库存任务模块')
assert.match(materialPanoramaDashboard, /MaterialPanoramaDocumentsModule/, '物料全景仪表台必须复用库位与文档任务模块')
assert.match(materialPanoramaDashboard, /MaterialPanoramaBomProcessModule/, '物料全景仪表台必须复用 BOM 与工艺任务模块')
assert.match(materialPanoramaDashboard, /MaterialPanoramaCostingModule/, '物料全景仪表台必须复用成本任务模块')
assert.match(materialPanoramaDashboard, /MaterialPanoramaOrdersModule/, '物料全景仪表台必须复用工单与领料任务模块')
assert.match(materialPanoramaDashboard, /MaterialPanoramaRecordsModule/, '物料全景仪表台必须复用来料与库存记录任务模块')
assert.match(materialPanoramaDashboard, /aria-expanded=\{expanded\}/, '物料全景详细资料必须提供可访问的折叠状态')
assert.match(materialPanoramaDashboard, /data-panorama-overview/, '物料全景桌面端必须提供左侧纵览区')
assert.match(materialPanoramaDashboard, /data-panorama-details/, '物料全景桌面端必须提供右侧明细区')
assert.match(materialPanoramaDashboard, /from '@\/app\/components\/layout'/, '物料全景主从布局必须复用公共页面布局出口')
assert.match(materialPanoramaDashboard, /<SplitWorkspace/, '物料全景桌面端必须复用公共左右主从布局')
assert.match(materialPanoramaDashboard, /primaryLabel="物料纵览"/, '物料全景左右区域必须提供明确语义')
assert.match(materialPanoramaDashboard, /maxPrimaryPercent=\{42\}/, '物料全景左栏最大宽度必须为右侧复杂明细保留可读空间')
assert.match(materialPanoramaOverview, /2xl:grid-cols-\[minmax\(0,1\.15fr\)_minmax\(360px,0\.85fr\)\]/, '档案与库存必须到超宽屏才并排，避免中等宽屏右侧明细被挤窄')
assert.match(materialPanoramaDashboard, /useState<PanoramaModuleId \| null>\(null\)/, '物料全景明细必须默认全部收起')
assert.match(materialPanoramaDashboard, /!modules\.some\(\(module\) => module\.visible && module\.id === activeSectionId\)/, '隐藏当前展开模块时必须同步清理活动明细状态')
assert.equal(togglePanoramaSection(null, 'summary'), 'summary', '收起状态点击明细必须展开目标组')
assert.equal(togglePanoramaSection('summary', 'costing'), 'costing', '切换明细时必须只保留新目标组')
assert.equal(togglePanoramaSection('costing', 'costing'), null, '再次点击当前明细必须收起')
assert.doesNotMatch(materialPanoramaDashboard, /全部展开/, '单组明细模式不得再提供全部展开')
assert.match(splitWorkspace, /try \{[\s\S]*localStorage\.getItem\(storageKey\)[\s\S]*\} catch \{[\s\S]*\} finally \{[\s\S]*setStorageReady\(true\)/, '公共分栏读取站点存储失败时必须恢复可见默认布局')
assert.match(splitWorkspace, /try \{[\s\S]*localStorage\.setItem\(storageKey, String\(primaryPercent\)\)[\s\S]*catch/, '公共分栏写入站点存储失败时必须保留当前会话布局')
assert.match(materialPanoramaPage, /MaterialPanoramaLayoutDialog/, '物料全景布局设置必须是独立任务组件')
assert.match(materialPanoramaPage, /MaterialPanoramaViewer/, '物料全景文件查看器必须是独立任务组件')
assert.match(materialPanoramaContracts, /export interface PanoramaData/, '物料全景响应结构必须集中为领域契约')
assert.match(materialPanoramaModel, /normalizePanoramaLayout/, '物料全景显示偏好规则必须集中为纯视图模型')
for (const source of [materialPanoramaDashboard, materialPanoramaOverview, materialPanoramaOperations, materialPanoramaRecords, materialPanoramaLayout, materialPanoramaViewer]) {
  assert.doesNotMatch(source, /fetch\(/, '物料全景展示任务不得直接访问远端数据')
}
assert.doesNotMatch(materialPage, /saveMaterial|importMaterials|findMaterialByCode|createEmptyMaterialForm/, '主物料页面不得重新承载详情读取、保存、导入或表单初始化状态')
assert.doesNotMatch(materialPage, /materials\.map/, '主物料页面不得重新展开卡片或表格行')
assert.doesNotMatch(materialPage, /mes-lite\.materials\.visibleFields|columnResizeCleanupRef/, '主物料页面不得重新承载视图偏好存储或列宽拖动状态')
assert.doesNotMatch(materialPage, /setDraftBom|convertBomEntryQuantity|normalizeBomEntryQuantity/, '主物料页面不得重新承载 BOM 草稿状态或单位换算')
assert.match(materialDetailDialog, /useMaterialDetail/, '物料详情切片必须通过专用控制器重新读取最新资料')
assert.match(materialDetailController, /findMaterialByCode/, '物料详情控制器必须拥有详情重新读取动作')
assert.match(materialDetailDialog, /MaterialReference/, '物料详情切片必须接受关联业务提供的轻量物料引用')
assert.match(materialDetailDialog, /AttachmentPanel/, '物料详情切片必须拥有图片附件视图')
assert.match(materialDetailDialog, /readOnly=\{!onEdit\}/, '只读物料详情不得暴露附件上传、设封面或归档命令')
assert.match(materialReferenceButton, /查看物料详情/, '物料引用入口必须提供明确的辅助说明')
assert.match(materialReferenceButton, /focus-visible:/, '物料引用入口必须保留键盘焦点反馈')
assert.match(materialDetailDialog, /className="[^"]*\bh-64\b[^"]*\bsm:h-80\b[^"]*\bmd:h-96\b[^"]*\bxl:h-\[28rem\][^"]*"/, '物料详情主图必须限制响应式高度，完整原图交由全屏或新窗口查看')
assert.doesNotMatch(materialDetailDialog, /aspect-\[4\/3\]/, '物料详情主图不得按全宽比例无限撑高弹窗')
assert.match(materialEditDialog, /saveMaterial/, '物料编辑切片必须拥有保存动作')
assert.match(materialEditDialog, /createMaterialForm/, '物料编辑切片必须拥有表单初始化')
assert.match(materialImportDialog, /importMaterials/, '物料导入切片必须拥有导入动作')
assert.match(materialOptions, /materialCategoryOptions/, '物料列表与编辑器必须复用领域选项定义')
assert.match(materialViewModel, /MaterialCollectionActions/, '物料集合视图必须通过稳定动作契约与主页面协作')
assert.match(materialCardView, /materials\.map/, '物料卡片视图必须拥有卡片集合渲染')
assert.match(materialTableView, /<table/, '物料表格视图必须拥有表格和列头渲染')
assert.match(materialPageOptions, /PageOptionsDialog/, '物料页内选项必须复用公共页面选项弹窗')
assert.match(materialPageOptions, /loadConfiguredUnits[\s\S]*from '@\/modules\/configuration'/, 'BOM 页内选项必须通过业务配置公开出口读取单位目录')
assert.match(materialPageOptions, /ToolbarOrderSettings/, '物料页内选项必须保留公共工具栏排序能力')
assert.match(materialViewPreferences, /window\.localStorage/, '物料视图偏好控制器必须拥有浏览器偏好持久化')
assert.match(materialViewPreferences, /MaterialColumnControls/, '物料视图偏好控制器必须提供稳定列宽控制契约')
assert.doesNotMatch(materialEditDialog, /fetch\(/, '物料编辑 UI 不得直接发起 HTTP 请求')
assert.doesNotMatch(materialImportDialog, /fetch\(/, '物料导入 UI 不得直接发起 HTTP 请求')
assert.doesNotMatch(materialDetailDialog, /fetch\(/, '物料详情 UI 必须通过领域 client 读取数据')
assert.doesNotMatch(materialCardView, /fetch\(/, '物料卡片视图不得读取远端数据')
assert.doesNotMatch(materialTableView, /fetch\(/, '物料表格视图不得读取远端数据')
assert.doesNotMatch(materialWorkspaceToolbar, /fetch\(/, '物料工具栏任务不得读取远端数据')
assert.doesNotMatch(materialBomWorkspace, /fetch\(/, 'BOM 工作区任务不得读取远端数据')
assert.match(materialWorkspaceToolbar, /pageKey="bomWorkspace"/, '双形态工具栏必须保留 BOM 工作区公共页面键')
assert.match(materialWorkspaceToolbar, /pageKey="materialManagement"/, '双形态工具栏必须保留物料管理公共页面键')
assert.match(materialBomWorkspace, /<BomDraftEditor/, 'BOM 工作区必须复用 BOM 草稿编辑器')
assert.doesNotMatch(bomOverview, /fetch\(/, 'BOM 全览 UI 不得直接发起 HTTP 请求')
assert.doesNotMatch(bomDraftEditor, /fetch\(/, 'BOM 草稿编辑器不得直接发起 HTTP 请求')
assert.match(bomDraftController, /saveBom\(/, 'BOM 草稿控制器必须拥有草稿保存用例')
assert.match(bomDraftModel, /isBomDraftDirty/, 'BOM 草稿脏状态必须由纯领域模型计算')
assert.match(materialClient, /fetch\('\/api\/materials/, '物料 HTTP 访问必须集中在 materials client')
assert.match(bomClient, /fetch\('\/api\/boms/, 'BOM HTTP 访问必须集中在 bom client')
assert.match(materialContracts, /export interface Material/, '物料数据结构必须集中为领域契约')
assert.ok(materialPanoramaRoute.split('\n').length <= 40, '物料全景 API 必须保持为不超过 40 行的 HTTP 适配层')
assert.doesNotMatch(materialPanoramaRoute, /prisma\.|findMany\(|withAttachmentUrls/, '物料全景 API 不得直接查询或装配附件')
assert.match(materialPanoramaRoute, /getMaterialPanorama\(/, '物料全景 API 必须通过领域查询服务读取')
assert.match(materialPanoramaQueryService, /Promise\.all/, '物料全景查询服务必须统一编排关联聚合')
assert.match(materialPanoramaQueryService, /classifyMaterialAttachments/, '物料全景查询服务必须复用附件分类器')
assert.match(materialPanoramaAttachmentService, /attachWorkInstructionFiles/, '物料全景附件服务必须统一装配正式作业文档附件')
const classifiedAttachments = classifyMaterialAttachments([
  { id: 'image', size: 1, rotation: 0, documentType: 'MATERIAL_IMAGE', originalName: 'part.png', note: null, mimeType: 'image/png' },
  { id: 'sop', size: 1, rotation: 0, documentType: 'OTHER', originalName: 'SOP.pdf', note: null, mimeType: 'application/pdf' },
])
assert.equal(classifiedAttachments.images.length, 1)
assert.equal(classifiedAttachments.workInstructions.length, 1)
assert.equal(classifiedAttachments.documents.length, 1)
assert.ok(materialImportRoute.split('\n').length <= 55, '物料导入 API 必须保持为不超过 55 行的 HTTP 适配层')
assert.doesNotMatch(materialImportRoute, /prisma\.|parseCsv|findCatalogUnit/, '物料导入 API 不得直接解析 CSV、校验单位或写数据库')
assert.match(materialImportRoute, /importMaterialsCsv\(/, '物料导入 API 必须通过领域导入服务执行')
assert.match(materialImportService, /prisma\.\$transaction/, '物料导入服务必须原子创建客户、物料和库存')
assert.match(materialImportService, /parseMaterialImportRows/, '物料导入服务必须复用纯解析规则')
assert.match(materialImportParser, /readMaterialImportSheet/, '物料导入解析器必须拥有表头与客户线索读取')
const importSheet = readMaterialImportSheet('物料编码,物料名称,库存单位,分类,主计量方式\nMAT-1,测试物料,件,成品,数量')
assert.ok(!('error' in importSheet), '有效物料 CSV 必须通过表头解析')
if (!('error' in importSheet)) {
  const importRows = parseMaterialImportRows({
    ...importSheet,
    customers: [],
    unitCatalog: presetUnitCatalog.map((unit, index) => ({ ...unit, sortOrder: index })),
  })
  assert.deepEqual(importRows.errors, [])
  assert.equal(importRows.materials[0].category, 'FINISHED')
  assert.equal(importRows.materials[0].primaryMeasure, 'QUANTITY')
}
assert.match(bomContracts, /export interface BomVersion/, 'BOM 数据结构必须集中为领域契约')
assert.doesNotMatch(bomContracts, /modules\/materials/, 'BOM 契约不得反向依赖 materials 模块形成类型环')
assert.ok(bomRoute.split('\n').length <= 70, 'BOM API 必须保持为不超过 70 行的 HTTP 适配层')
assert.doesNotMatch(bomRoute, /prisma\.|normalizeBomEntryQuantity|resolveProductId/, 'BOM API 不得直接执行查询、单位换算或写入事务')
assert.match(bomRoute, /listBoms\(/, 'BOM API 必须通过查询服务读取列表')
assert.match(bomRoute, /saveBom\(/, 'BOM API 必须通过命令服务保存方案')
assert.match(bomQueryService, /withMaterialImageUrls/, 'BOM 查询服务必须拥有主图与库存摘要装配')
assert.match(bomCommandService, /validateBomStructure\(/, 'BOM 命令服务必须调用纯结构规则')
assert.match(bomCommandService, /prisma\.\$transaction/, 'BOM 命令服务必须原子替换投入与产出')
assert.match(bomLifecycleService, /status: 'RELEASED'/, 'BOM 生命周期服务必须显式发布版本')
assert.match(bomLifecycleService, /status: 'OBSOLETE'/, 'BOM 生命周期服务必须显式作废版本')
assert.match(bomLifecycleService, /status: 'DRAFT'/, 'BOM 复制新版本必须回到草稿态')
for (const route of [bomReleaseRoute, bomCopyRoute, bomObsoleteRoute]) {
  assert.doesNotMatch(route, /prisma\./, 'BOM 生命周期 API 不得直接读写数据库')
  assert.match(route, /writeAuditLog\(/, 'BOM 发布、复制和作废必须写入审计')
}
assert.match(bomSchema, /export const saveBomSchema/, 'BOM 写入 Schema 必须归属领域契约')
assert.equal(nextBomVersion(['v1', 'V3', 'draft']), 'v4')
assert.equal(validateBomStructure({
  purpose: 'PRODUCTION', outputs: [{ materialId: 'out', isPrimary: true }], inputMaterialIds: ['in'],
}), null)
assert.equal(validateBomStructure({
  purpose: 'PRODUCTION', outputs: [{ materialId: 'same', isPrimary: true }], inputMaterialIds: ['same'],
}), 'BOM 投入与产出不能使用同一物料；同物料跨库位请使用流程转移')
assert.equal(validateBomStructure({
  purpose: 'PACKAGING', outputs: [{ materialId: 'a', isPrimary: true }, { materialId: 'b' }], inputMaterialIds: ['in'],
}), '包装 BOM 必须且只能设置一项产出')

assert.ok(materialPage.split('\n').length <= 750, '物料页面已拆出工具栏和 BOM 工作区，不得再超过 750 行')
assert.ok(materialWorkspaceToolbar.split('\n').length <= 120, '物料双形态工具栏应保持纯装配职责')
assert.ok(materialBomWorkspace.split('\n').length <= 120, 'BOM 工作区视图不得承载草稿状态或远端请求')
assert.ok(materialPanoramaPage.split('\n').length <= 250, '物料全景协调页不得重新承载业务模块正文或独立弹层')
assert.ok(materialPanoramaDashboard.split('\n').length <= 180, '物料全景仪表台应只负责编排关键指标和折叠模块')
assert.ok(materialPanoramaOverview.split('\n').length <= 140, '物料全景档案与文档模块应保持纯展示职责')
assert.ok(materialPanoramaOperations.split('\n').length <= 170, '物料全景 BOM、成本与工单模块应保持纯展示职责')
assert.ok(materialPanoramaRecords.split('\n').length <= 80, '物料全景记录模块应保持纯展示职责')
assert.ok(materialCardView.split('\n').length <= 150, '物料卡片视图应保持纯展示职责')
assert.ok(materialTableView.split('\n').length <= 280, '物料表格视图不得承载页面级状态')
assert.ok(materialPagination.split('\n').length <= 80, '物料分页视图应保持纯展示职责')
assert.ok(materialPageOptions.split('\n').length <= 220, '物料页内选项不得承载业务查询或页面导航状态')
assert.ok(materialViewPreferences.split('\n').length <= 230, '物料视图偏好控制器应只维护本地显示状态')
assert.ok(materialViewModel.split('\n').length <= 130, '物料视图模型只能维护稳定选项和类型')
assert.ok(materialPanoramaQueryService.split('\n').length <= 220, '物料全景查询服务不得膨胀为第二个巨型路由')
assert.ok(materialPanoramaAttachmentService.split('\n').length <= 80, '物料全景附件分类与装配应保持聚焦')
assert.ok(materialImportParser.split('\n').length <= 180, '物料导入解析规则应保持为可测试的纯领域逻辑')
assert.ok(materialImportService.split('\n').length <= 160, '物料导入服务应聚焦客户匹配、单位锁定和原子写入')
assert.ok(materialDetailDialog.split('\n').length <= 180, '物料详情切片不得重新膨胀为页面级巨型组件')
assert.ok(materialEditDialog.split('\n').length <= 450, '物料编辑切片不得重新膨胀为页面级巨型组件')
assert.ok(materialImportDialog.split('\n').length <= 160, '物料导入切片应保持单一职责')
assert.ok(bomOverview.split('\n').length <= 500, 'BOM 全览页面不得超过 500 行')
assert.ok(bomDraftEditor.split('\n').length <= 450, 'BOM 草稿编辑器只能维护编辑交互和展示')
assert.ok(bomDraftController.split('\n').length <= 500, 'BOM 草稿控制器不得膨胀为新的页面组件')
assert.ok(bomDraftModel.split('\n').length <= 120, 'BOM 草稿纯规则必须保持聚焦')
assert.ok(bomCommandService.split('\n').length <= 220, 'BOM 命令服务应聚焦校验、换算和原子替换')
assert.ok(bomLifecycleService.split('\n').length <= 160, 'BOM 生命周期服务应聚焦发布、复制和作废')
assert.ok(bomQueryService.split('\n').length <= 100, 'BOM 查询服务应聚焦资料与摘要装配')

console.log('物料/BOM 模块边界验证通过：数据访问、物料切片、全景任务、BOM 草稿控制器、领域规则和编辑器职责已分离。')
